module: src/measures.py
method: cluster_jsd
clustering: 
  module: src/clustering.py
  method: clustering_correlation
  params:
    max_senses: 10
    max_attempts: 200
    max_iters: 5000
    initial: []
    split_flag: True