n_jobs: 7

# allows to hard-code backend, otherwise inferred based on prefer and require
backend: null

# processes or threads, soft hint to choose backend
prefer: "processes"

# null or sharedmem, sharedmem will select thread-based backend
require: null

# if greater than zero, prints progress messages
verbose: 0

# timeout limit for each task. Unit dependent on backend implementation; miliseconds for loky.
timeout: null

# number of batches to be pre-dispatched
pre_dispatch: "2*n_jobs"

# number of atomic tasks to dispatch at once to each worker
batch_size:  "auto"

# path used for memmapping large arrays for sharing memory with workers
temp_folder: None

# thresholds size of arrays that triggers automated memmapping
max_nbytes: None

# memmapping mode for numpy arrays passed to workers
mmap_mode: "r"