name: xlmr
model: xlm-roberta-base
layers: [1, -1]
measure: apd
subword_aggregation: average # one of [first, average]
#measure: apd   # what we do with the vectors once we have them (apd, cos, cluster)
