defaults:
  - scaler: none
  - normalization: none
  - metric@similarity_metric: ???

_target_: src.wic.ContextualEmbedder
layers: [1, 12]
layer_aggregation: average
subword_aggregation: average
truncation_tokens_before_target: 0.5
encode_only: false
embedding_scope: sentence

gpu: null
ckpt: ???

# prediction_cache:
#   _target_: src.wic.contextual_embedder.PredictionCache
#   metadata:
#     dataset:
#       name: ${dataset.name}
#       preprocessing: ${dataset.preprocessing.name}
#       spelling_normalization: ${dataset.spelling_normalization}
#     contextual_embedder:
#       pre_target_tokens: ${....truncation_tokens_before_target}
#       ckpt: ${....ckpt}
#       layers: ${....layers}
#       layer_aggregation: ${....layer_aggregation}
#       subword_aggregation: ${....subword_aggregation}
#       normalization: ${....normalization}
#       scaler: ${....scaler}
#       similarity_metric: ${....similarity_metric}

embedding_cache:
  _target_: src.wic.contextual_embedder.EmbeddingCache
  metadata:
    dataset:
      name: ${dataset.name}
      preprocessing: ${dataset.preprocessing.name}
      spelling_normalization: ${dataset.spelling_normalization}
    contextual_embedder:
      pre_target_tokens: ${....truncation_tokens_before_target}
      ckpt: ${....ckpt}


