defaults:
  - plotter: histogram

_target_: src.evaluation.LSCDGradedEvaluation
exclude_annotators: []
task: change_graded
metric: 
  _target_: src.wrappers.spearmanr
  _partial_: true
  nan_policy: omit