# the Dataset class also requires a `standard_split` argument
# however, Hydra cannot interpolate values in the defaults list with values 
# in the final config (i.e., outside the defaults list)
# therefore this field is added at runtime in utils/runner.py

defaults:
  - _self_
  - preprocessing: toklem
  - spelling_normalization: german

name: dwug_de
cleaning: null
test_on: null
groupings: ["1", "2"]
version: "1.1.0"
pairing: [COMPARE]
sampling: [annotated]


urls:
  "1.1.0": "https://zenodo.org/record/5791193/files/diawug.zip"
  "1.0.0": "https://zenodo.org/record/5544554/files/diawug.zip"

_target_: src.dataset.Dataset

