_target_: src.dataset.Dataset
cleaning: null
defaults:
- _self_
- preprocessing: toklem
- spelling_normalization: german
exclude_annotators: []
groupings:
- '1'
- '2'
pairing:
- COMPARE
sampling:
- annotated
test_on: null
path: diawug_100
type: test
split: undefined
url: https://zenodo.org/record/5544554/files/diawug.zip