defaults:
  - preprocessing: toklem
  - spelling_normalization: german

name: dwug_de
bert: bert-base-german-cased
cleaning: null
test_on: null
groupings: ["1", "2"]
version: "1.1.0"
pairing: [COMPARE]
sampling: [annotated]

urls:
  "1.1.0": "https://zenodo.org/record/5791193/files/diawug.zip",
  "1.0.0": "https://zenodo.org/record/5544554/files/diawug.zip"

_target_: src.dataset.Dataset

