_target_: src.dataset.Dataset
cleaning: null
defaults:
- _self_
- preprocessing: toklem
- spelling_normalization: german
exclude_annotators: []
groupings:
- '1'
- '2'
name: discowug
pairing:
- COMPARE
sampling:
- annotated
split:
  how: standard
  use: dev
test_on: null
version: 1.1.0
versions:
  1.0.0:
    path: discowug/1.0.0
    standard_split:
      dev:
      - Berücksichtigung
      - Kunde
      - hinrichten
      - Aufrichtung
      - Angesicht
      - Bemerken
      - Fischerei
      - gelagert
      - Westen
      - niederschlagen
      - Lebenslage
      - Überflutung
      - geehrt
      - freigelaßen
      - Ächtung
      - eintreten
      - Triebkraft
      - ausbilden
      - Vorbereitung
      - ungebrechen
      - Handhabe
      - nebensächlich
      - Rang
      - hochwichtig
      - Lager
      - helfen
      - Warschauer
      - Zurückgebleibene
      - Aufkommen
      - zurückwerfen
      - erlauben
      - Mauer
      - Angriffswaffe
      - Vernichtungskrieg
      - finnisch
      - neunjahrig
      - wuchernd
      - Zuwachs
      test:
      - Waffenruhe
      - angeregt
      - greifend
      - Kölner
      - anpflanzen
      - freistehend
      - Losung
      - preisgeben
      - erringen
      - Ausrufung
      - einbinden
      - nochmalig
      - Aussterben
      - gewahren
      - Zehner
      - Formgebung
      - aufstrebend
      - durchdenken
      - Kompanie
      - überwintern
      - Hauptfrage
      - regelrecht
      - Kriegskunst
      - Querschnitt
      - Walzwerk
      - Königreich
      - einmünden
      - Rädelsführer
      - Tote
      - vorjährig
      - unbedenklich
      - Arbeitsbedingung
      - Täter
      - regulär
      - abspalten
      - Vernehmen
      - Sprachrohr
    url: https://zenodo.org/record/5544580/files/discowug.zip
  1.1.0:
    path: discowug/1.1.0
    standard_split:
      dev:
      - finnisch
      - Lebenslage
      - greifend
      - Fischerei
      - Sprachrohr
      - freistehend
      - regelrecht
      - Kompanie
      - Königreich
      - erringen
      - wuchernd
      - Lager
      - Aussterben
      - Aufrichtung
      - Rädelsführer
      - Querschnitt
      - Zehner
      - Westen
      - anpflanzen
      - Zuwachs
      - Aufkommen
      - Mauer
      - Tote
      - niederschlagen
      - Formgebung
      - Triebkraft
      - aufstrebend
      - einmünden
      - Kölner
      - Rang
      - zurückwerfen
      - Angriffswaffe
      - freigelaßen
      - ungebrechen
      - nochmalig
      - Angesicht
      - Überflutung
      - Vernehmen
      test:
      - Waffenruhe
      - erlauben
      - angeregt
      - Berücksichtigung
      - Zurückgebleibene
      - Warschauer
      - hinrichten
      - Losung
      - preisgeben
      - Ausrufung
      - einbinden
      - gewahren
      - hochwichtig
      - helfen
      - ausbilden
      - Ächtung
      - Kunde
      - Vernichtungskrieg
      - durchdenken
      - überwintern
      - Bemerken
      - eintreten
      - Hauptfrage
      - Kriegskunst
      - neunjahrig
      - nebensächlich
      - Vorbereitung
      - Walzwerk
      - Handhabe
      - geehrt
      - vorjährig
      - gelagert
      - unbedenklich
      - Arbeitsbedingung
      - Täter
      - regulär
      - abspalten
    url: https://zenodo.org/record/5791125/files/discowug.zip
