_target_: src.dataset.Dataset
cleaning: null
defaults:
  - _self_
  - preprocessing: ???
  - spelling_normalization: ???
  - split: ???
exclude_annotators: []
groupings:
  - "1"
  - "2"
wic_use_pairs:
  group: ALL
  sample: annotated
path: discowug_110
standard_split:
  dev: []
  dev1: []
  dev2: []
  full:
    - abspalten
    - angeregt
    - Angesicht
    - Angriffswaffe
    - anpflanzen
    - Arbeitsbedingung
    - Aufkommen
    - Aufrichtung
    - aufstrebend
    - ausbilden
    - Ausrufung
    - Aussterben
    - Ächtung
    - Bemerken
    - Berücksichtigung
    - durchdenken
    - einbinden
    - einmünden
    - eintreten
    - erlauben
    - erringen
    - finnisch
    - Fischerei
    - Formgebung
    - freigelaßen
    - freistehend
    - geehrt
    - gelagert
    - gewahren
    - greifend
    - Handhabe
    - Hauptfrage
    - helfen
    - hinrichten
    - hochwichtig
    - Kompanie
    - Kölner
    - Königreich
    - Kriegskunst
    - Kunde
    - Lager
    - Lebenslage
    - Losung
    - Mauer
    - nebensächlich
    - neunjahrig
    - niederschlagen
    - nochmalig
    - preisgeben
    - Querschnitt
    - Rang
    - Rädelsführer
    - regelrecht
    - regulär
    - Sprachrohr
    - Täter
    - Tote
    - Triebkraft
    - unbedenklich
    - ungebrechen
    - Überflutung
    - überwintern
    - Vernehmen
    - Vernichtungskrieg
    - Vorbereitung
    - vorjährig
    - Waffenruhe
    - Walzwerk
    - Warschauer
    - Westen
    - wuchernd
    - Zehner
    - Zurückgebleibene
    - zurückwerfen
    - Zuwachs
  test:
    - abspalten
    - angeregt
    - Angesicht
    - Angriffswaffe
    - anpflanzen
    - Arbeitsbedingung
    - Aufkommen
    - Aufrichtung
    - aufstrebend
    - ausbilden
    - Ausrufung
    - Aussterben
    - Ächtung
    - Bemerken
    - Berücksichtigung
    - durchdenken
    - einbinden
    - einmünden
    - eintreten
    - erlauben
    - erringen
    - finnisch
    - Fischerei
    - Formgebung
    - freigelaßen
    - freistehend
    - geehrt
    - gelagert
    - gewahren
    - greifend
    - Handhabe
    - Hauptfrage
    - helfen
    - hinrichten
    - hochwichtig
    - Kompanie
    - Kölner
    - Königreich
    - Kriegskunst
    - Kunde
    - Lager
    - Lebenslage
    - Losung
    - Mauer
    - nebensächlich
    - neunjahrig
    - niederschlagen
    - nochmalig
    - preisgeben
    - Querschnitt
    - Rang
    - Rädelsführer
    - regelrecht
    - regulär
    - Sprachrohr
    - Täter
    - Tote
    - Triebkraft
    - unbedenklich
    - ungebrechen
    - Überflutung
    - überwintern
    - Vernehmen
    - Vernichtungskrieg
    - Vorbereitung
    - vorjährig
    - Waffenruhe
    - Walzwerk
    - Warschauer
    - Westen
    - wuchernd
    - Zehner
    - Zurückgebleibene
    - zurückwerfen
    - Zuwachs
test_on: null
type: test
url: https://zenodo.org/record/5791125/files/discowug.zip
