defaults:
  - _self_
  - preprocessing: toklem
  - spelling_normalization: german
  - standard_split: ${dataset}_${version}

name: dwug_de
cleaning: null
test_on: null
groupings: ["1", "2"]
version: "3.0.0"
pairing: [COMPARE]
sampling: [annotated]

urls:
  "3.0.0": "https://zenodo.org/record/5784453/files/durel.zip"
  "2.1.0": "https://zenodo.org/record/5554145/files/durel.zip"
  "2.0.0": "https://zenodo.org/record/5541340/files/durel.zip"
  # "1.0.0": "https://zenodo.org/record/5541275/files/DURel.zip"

_target_: src.dataset.Dataset


