_target_: src.dataset.Dataset
cleaning: null
defaults:
- _self_
- preprocessing: toklem
- spelling_normalization: german
exclude_annotators: []
groupings:
- '1'
- '2'
pairing:
- COMPARE
path: durel_210
sampling:
- annotated
split: undefined
standard_split:
  dev: []
  dev1: []
  dev2: []
  full:
  - Abend
  - Anstalt
  - Anstellung
  - Bilanz
  - billig
  - Donnerwetter
  - englisch
  - Feder
  - Feine
  - flott
  - geharnischt
  - Kinderstube
  - locker
  - Motiv
  - Museum
  - packen
  - Presse
  - Reichstag
  - Steckenpferd
  - technisch
  - Vorwort
  - Zufall
  test:
  - Abend
  - Anstalt
  - Anstellung
  - Bilanz
  - billig
  - Donnerwetter
  - englisch
  - Feder
  - Feine
  - flott
  - geharnischt
  - Kinderstube
  - locker
  - Motiv
  - Museum
  - packen
  - Presse
  - Reichstag
  - Steckenpferd
  - technisch
  - Vorwort
  - Zufall
test_on: null
type: test
url: https://zenodo.org/record/5554145/files/durel.zip
