# the Dataset class also requires a `standard_split` argument
# however, Hydra cannot interpolate values in the defaults list with values 
# in the final config (i.e., outside the defaults list)
# therefore this field is added at runtime in utils/runner.py

defaults:
  - _self_
  - preprocessing: toklem
  - spelling_normalization: german

name: dwug_de
cleaning: null
test_on: null
groupings: ["1", "2"]
version: "3.0.0"
pairing: [COMPARE]
sampling: [annotated]

urls:
  "3.0.0": "https://zenodo.org/record/5784453/files/durel.zip"
  "2.1.0": "https://zenodo.org/record/5554145/files/durel.zip"
  "2.0.0": "https://zenodo.org/record/5541340/files/durel.zip"
  # "1.0.0": "https://zenodo.org/record/5541275/files/DURel.zip" # does not contain a data/ folder

_target_: src.dataset.Dataset


