defaults:
  - preprocessing/spelling_normalization: null

name: dwug_en
cleaning: null
preprocessing:
  _target_: src.preprocessing.Toklem
  params: {}
test_targets: null
groupings: ["1", "2"]
version: 'latest'

_target_: src.dataset.Dataset