_target_: src.dataset.Dataset
cleaning: null
defaults:
- preprocessing: toklem
- spelling_normalization: german
exclude_annotators: []
groupings:
- '1'
- '2'
pairing:
- COMPARE
path: dwug_de_200
sampling:
- annotated
type: dev
split: undefined
test_on: null
url: https://zenodo.org/record/5796871/files/dwug_de.zip
