_target_: src.dataset.Dataset
cleaning: null
defaults:
- _self_
- preprocessing: toklem
- spelling_normalization: swedish
exclude_annotators: []
groupings:
- '1'
- '2'
name: dwug_sv
pairing:
- COMPARE
sampling:
- annotated
split:
  how: standard
  use: dev
test_on: null
version: 2.0.0
versions:
  1.0.0:
    path: dwug_sv/1.0.0
    standard_split:
      dev:
      - blockera
      - kemisk
      - bolagsstämma
      - ledning
      - stöt
      - bedömande
      - fången
      - vaktmästare
      - notis
      - förhandling
      - anda
      - gagn
      - framlida
      - aktiv
      - bearbeta
      - annandag
      - studie
      - bröllop
      - gloria
      - uppfattning
      - uppslag
      - vegetation
      test:
      - konduktör
      - mode
      - bäck
      - undertrycka
      - krita
      - ingående
      - medium
      - färg
      - kokärt
      - uppläggning
      - central
      - by
      - beredning
      - motiv
      - uppfostran
      - uträtta
      - antyda
      - sittning
      - fack
      - dun
      - granskare
      - jordisk
    url: https://zenodo.org/record/5090648/files/dwug_sv.zip
  2.0.0:
    path: dwug_sv/2.0.0
    standard_split:
      dev:
      - undertrycka
      - studie
      - central
      - krita
      - fack
      - ledning
      - bedömande
      - granskare
      - annandag
      - beredning
      - förhandling
      - medium
      - motiv
      - konduktör
      - by
      - framlida
      - jordisk
      - vaktmästare
      - stöt
      - uppfattning
      - anda
      - dun
      test:
      - mode
      - bäck
      - blockera
      - vegetation
      - ingående
      - aktiv
      - gloria
      - färg
      - kokärt
      - uppläggning
      - kemisk
      - bearbeta
      - fången
      - uppfostran
      - uträtta
      - bröllop
      - bolagsstämma
      - antyda
      - sittning
      - uppslag
      - gagn
      - notis
    url: https://zenodo.org/record/5801358/files/dwug_sv.zip
