_target_: src.dataset.Dataset
cleaning: null
defaults:
  - preprocessing: toklem
  - spelling_normalization: german
exclude_annotators: []
groupings:
  - "1"
  - "2"
wic_use_pairs:
  group: ALL
  sample: annotated
split: undefined
path: dwug_de_sense
standard_split:
  dev:
    - abbauen
    - abdecken
    - abgebrüht
    - Abgesang
    - Ackergerät
    - Armenhaus
    - artikulieren
    - aufrechterhalten
    - Ausnahmegesetz
    - ausspannen
    - Behandlung
    - beimischen
    - Dynamik
    - Einreichung
    - Eintagsfliege
    - Engpaß
    - Entscheidung
    - Festspiel
    - Frechheit
    - Fuß
    - Gesichtsausdruck
    - Knotenpunkt
    - Kubikmeter
    - Lyzeum
    - Manschette
    - Mißklang
    - Mulatte
    - Mut
    - Naturschönheit
    - Ohrwurm
    - Pachtzins
    - packen
    - Rezeption
    - Schmiere
    - Seminar
    - Sensation
    - Spielball
    - Tier
    - Titel
    - Tragfähigkeit
    - Truppenteil
    - Unentschlossenheit
    - verbauen
    - vergönnen
    - voranstellen
    - vorliegen
    - vorweisen
    - weitgreifend
    - zersetzen
    - überspannen
  dev1:
    - Mulatte
    - vorliegen
    - Manschette
    - Sensation
    - Tier
    - Lyzeum
    - Frechheit
    - voranstellen
    - Mißklang
    - Kubikmeter
    - Gesichtsausdruck
    - vorweisen
    - Entscheidung
    - abgebrüht
    - Knotenpunkt
    - Rezeption
    - abdecken
    - Dynamik
    - Einreichung
    - weitgreifend
    - zersetzen
    - Fuß
    - Festspiel
    - Armenhaus
    - Titel
  dev2:
    - artikulieren
    - abbauen
    - Ausnahmegesetz
    - Tragfähigkeit
    - Eintagsfliege
    - ausspannen
    - überspannen
    - Ackergerät
    - Engpaß
    - Mut
    - packen
    - Abgesang
    - Seminar
    - vergönnen
    - Ohrwurm
    - Truppenteil
    - Unentschlossenheit
    - Behandlung
    - Pachtzins
    - Naturschönheit
    - Spielball
    - beimischen
    - verbauen
    - aufrechterhalten
    - Schmiere
  full:
    - abbauen
    - abdecken
    - abgebrüht
    - Abgesang
    - Ackergerät
    - Armenhaus
    - artikulieren
    - aufrechterhalten
    - Ausnahmegesetz
    - ausspannen
    - Behandlung
    - beimischen
    - Dynamik
    - Einreichung
    - Eintagsfliege
    - Engpaß
    - Entscheidung
    - Festspiel
    - Frechheit
    - Fuß
    - Gesichtsausdruck
    - Knotenpunkt
    - Kubikmeter
    - Lyzeum
    - Manschette
    - Mißklang
    - Mulatte
    - Mut
    - Naturschönheit
    - Ohrwurm
    - Pachtzins
    - packen
    - Rezeption
    - Schmiere
    - Seminar
    - Sensation
    - Spielball
    - Tier
    - Titel
    - Tragfähigkeit
    - Truppenteil
    - Unentschlossenheit
    - verbauen
    - vergönnen
    - voranstellen
    - vorliegen
    - vorweisen
    - weitgreifend
    - zersetzen
    - überspannen
  test: []
test_on: null
type: dev
url: https://zenodo.org/record/7386402/files/dwug_de.zip
