_target_: src.dataset.Dataset
cleaning: null
defaults:
- _self_
- preprocessing: toklem
exclude_annotators: []
groupings:
- '1'
- '2'
name: dwug_es
pairing:
- COMPARE
sampling:
- annotated
spelling_normalization: null
split:
  how: standard
  use: dev
test_on: null
version: 4.0.0
versions:
  1.0.0:
    path: dwug_es/1.0.0
    standard_split:
      dev:
      - albergar
      - descendiente
      - escritor
      - arena
      - músculo
      - despacho
      - sexo
      - servidor
      - quemar
      - precursor
      test:
      - corona
      - aguantar
      - verdaderamente
      - contingente
      - reforma
      - intolerable
      - pelear
      - móvil
      - periodista
      - corredor
    url: https://zenodo.org/record/6300105/files/dwug_es.zip
  1.0.1:
    path: dwug_es/1.0.1
    standard_split:
      dev:
      - quemar
      - corredor
      - contingente
      - periodista
      - móvil
      - intolerable
      - pelear
      - aguantar
      - músculo
      - corona
      test:
      - descendiente
      - albergar
      - verdaderamente
      - arena
      - despacho
      - reforma
      - precursor
      - escritor
      - sexo
      - servidor
    url: https://zenodo.org/record/6433203/files/dwug_es.zip
  2.0.0:
    path: dwug_es/2.0.0
    standard_split:
      dev:
      - mujer
      - empresa
      - saludar
      - propuesta
      - nombramiento
      - obtener
      - abundar
      - 'no'
      - modo
      - interrogatorio
      test:
      - suposición
      - creciente
      - mortal
      - asolar
      - tablero
      - agradecer
      - instalación
      - gracioso
      - pretender
      - adelante
    url: https://zenodo.org/record/6433350/files/dwug_es.zip
  3.0.0:
    path: dwug_es/3.0.0
    standard_split:
      dev:
      - tarea
      - capital
      - atrás
      - demá
      - corriente
      - fallar
      - diligencia
      - retroceder
      - trato
      - prima
      - canal
      - cobrar
      - declinar
      - historia
      - educado
      - próximo
      - metal
      - tropical
      - médula
      - pendiente
      - recordar
      - compasión
      - historiador
      - colaborar
      - juguete
      - enterar
      - susceptible
      - disco
      - modificado
      - variedad
      test:
      - vuestro
      - pila
      - impulso
      - solicitud
      - banco
      - ataque
      - socialista
      - distribuir
      - cólera
      - actitud
      - encargado
      - fallecimiento
      - satélite
      - ausencia
      - avance
      - metro
      - maravilloso
      - visita
      - copiar
      - indicativo
      - especulación
      - maduro
      - marco
      - recomendar
      - viernes
      - planta
      - elocuente
      - nombrar
      - propiamente
      - matiz
    url: https://zenodo.org/record/6433398/files/dwug_es.zip
  4.0.0:
    path: dwug_es/4.0.0
    standard_split:
      dev:
      - elocuente
      - tropical
      - nombrar
      - visita
      - empresa
      - maduro
      - distribuir
      - propiamente
      - encargado
      - compasión
      - modo
      - prima
      - reforma
      - enterar
      - modificado
      - arena
      - móvil
      - recomendar
      - demá
      - cólera
      - verdaderamente
      - diligencia
      - médula
      - corredor
      - metal
      - aguantar
      - especulación
      - adelante
      - impulso
      - susceptible
      - corona
      - pila
      - banco
      - juguete
      - mujer
      - pendiente
      - recordar
      - pelear
      - próximo
      - educado
      - metro
      - indicativo
      - variedad
      - agradecer
      - mortal
      - colaborar
      - periodista
      - gracioso
      - vuestro
      - ausencia
      test:
      - historiador
      - solicitud
      - despacho
      - tablero
      - historia
      - atrás
      - escritor
      - fallar
      - interrogatorio
      - capital
      - sexo
      - avance
      - descendiente
      - corriente
      - copiar
      - nombramiento
      - marco
      - tarea
      - planta
      - instalación
      - precursor
      - contingente
      - canal
      - suposición
      - propuesta
      - ataque
      - socialista
      - disco
      - actitud
      - fallecimiento
      - 'no'
      - asolar
      - intolerable
      - satélite
      - pretender
      - maravilloso
      - saludar
      - creciente
      - retroceder
      - quemar
      - músculo
      - viernes
      - declinar
      - cobrar
      - abundar
      - trato
      - matiz
      - albergar
      - servidor
      - obtener
    url: https://zenodo.org/record/6433667/files/dwug_es.zip
