defaults:
  - preprocessing: toklem
  - spelling_normalization: null

name: dwug_sv
bert: KB/bert-base-swedish-cased
cleaning: null
test_on: null
groupings: ["1", "2"]
version: 2.0.0

_target_: src.dataset.Dataset