# the Dataset class also requires a `standard_split` argument
# however, Hydra cannot interpolate values in the defaults list with values 
# in the final config (i.e., outside the defaults list)
# therefore this field is added at runtime in utils/runner.py

defaults:
  - preprocessing: toklem
  - spelling_normalization: german

name: dwug_de
cleaning: null
test_on: null
groupings: ["1", "2"]
version: "2.1.0"
standard_split: ${.name}_${.version}
pairing: [COMPARE]
sampling: [annotated]
split:
  how: standard
  use: ???

urls:
  "2.1.0": "https://zenodo.org/record/7295410/files/dwug_de.zip"
  "2.0.0": "https://zenodo.org/record/5796871/files/dwug_de.zip"
  "1.1.0": "https://zenodo.org/record/5544198/files/dwug_de.zip"
  "1.0.0": "https://zenodo.org/record/5543724/files/dwug_de.zip"

_target_: src.dataset.Dataset