defaults:
  - preprocessing: toklem
  - override preprocessing/spelling_normalization: german

name: dwug_de
bert: bert-base-german-cased
cleaning: null
test_on: null
groupings: ["1", "2"]
version: 2.0.0

_target_: src.dataset.Dataset