_target_: src.dataset.Dataset
cleaning: null
defaults:
- _self_
- preprocessing: toklem
exclude_annotators: []
groupings:
- '1'
- '2'
pairing:
- COMPARE
path: dwug_es_200
sampling:
- annotated
spelling_normalization: null
split: undefined
standard_split:
  dev: []
  dev1: []
  dev2: []
  full:
  - abundar
  - adelante
  - agradecer
  - asolar
  - creciente
  - empresa
  - gracioso
  - instalaci贸n
  - interrogatorio
  - modo
  - mortal
  - mujer
  - 'no'
  - nombramiento
  - obtener
  - pretender
  - propuesta
  - saludar
  - suposici贸n
  - tablero
  test:
  - abundar
  - adelante
  - agradecer
  - asolar
  - creciente
  - empresa
  - gracioso
  - instalaci贸n
  - interrogatorio
  - modo
  - mortal
  - mujer
  - 'no'
  - nombramiento
  - obtener
  - pretender
  - propuesta
  - saludar
  - suposici贸n
  - tablero
test_on: null
type: test
url: https://zenodo.org/record/6433350/files/dwug_es.zip
