_target_: src.dataset.Dataset
cleaning: null
defaults:
- preprocessing: toklem
- spelling_normalization: german
exclude_annotators: []
groupings:
- '1'
- '2'
name: dwug_de
pairing:
- COMPARE
sampling:
- annotated
split:
  how: standard
  use: dev
test_on: null
version: 2.1.0
versions:
  1.0.0:
    path: dwug_de/1.0.0
    standard_split:
      dev:
      - Tragfähigkeit
      - Rezeption
      - Tier
      - aufrechterhalten
      - artikulieren
      - Lyzeum
      - Sensation
      - Titel
      - abgebrüht
      - verbauen
      - überspannen
      - Seminar
      - Mut
      - Frechheit
      - Truppenteil
      - Pachtzins
      - Spielball
      - ausspannen
      - voranstellen
      - zersetzen
      - Knotenpunkt
      - packen
      - weitgreifend
      - abdecken
      - Gesichtsausdruck
      test:
      - vorweisen
      - Unentschlossenheit
      - vorliegen
      - Einreichung
      - Engpaß
      - Naturschönheit
      - Ohrwurm
      - Kubikmeter
      - Behandlung
      - vergönnen
      - Mulatte
      - Dynamik
      - Entscheidung
      - Manschette
      - Mißklang
      - Schmiere
      - Ackergerät
      - Festspiel
      - abbauen
      - beimischen
      - Eintagsfliege
      - Armenhaus
      - Fuß
      - Ausnahmegesetz
      - Abgesang
    url: https://zenodo.org/record/5543724/files/dwug_de.zip
  1.1.0:
    path: dwug_de/1.1.0
    standard_split:
      dev:
      - Frechheit
      - Unentschlossenheit
      - Armenhaus
      - Einreichung
      - Titel
      - Ohrwurm
      - Mißklang
      - Sensation
      - Behandlung
      - Abgesang
      - Tier
      - Naturschönheit
      - Ackergerät
      - Spielball
      - abbauen
      - überspannen
      - ausspannen
      - Knotenpunkt
      - Rezeption
      - Kubikmeter
      - Schmiere
      - Tragfähigkeit
      - Fuß
      - Festspiel
      - Mut
      test:
      - vorweisen
      - abgebrüht
      - artikulieren
      - vorliegen
      - Engpaß
      - weitgreifend
      - Gesichtsausdruck
      - packen
      - Seminar
      - Truppenteil
      - vergönnen
      - Mulatte
      - Dynamik
      - Entscheidung
      - Manschette
      - zersetzen
      - Lyzeum
      - beimischen
      - Eintagsfliege
      - aufrechterhalten
      - voranstellen
      - Pachtzins
      - Ausnahmegesetz
      - verbauen
      - abdecken
    url: https://zenodo.org/record/5544198/files/dwug_de.zip
  2.0.0:
    path: dwug_de/2.0.0
    standard_split:
      dev:
      - Engpaß
      - Eintagsfliege
      - Titel
      - Frechheit
      - Pachtzins
      - Mulatte
      - abdecken
      - packen
      - vergönnen
      - Rezeption
      - überspannen
      - aufrechterhalten
      - Fuß
      - Tier
      - Ausnahmegesetz
      - Ohrwurm
      - Manschette
      - abgebrüht
      - abbauen
      - Seminar
      - Naturschönheit
      - voranstellen
      - weitgreifend
      - Entscheidung
      - verbauen
      test:
      - ausspannen
      - zersetzen
      - Kubikmeter
      - Dynamik
      - Tragfähigkeit
      - Festspiel
      - Behandlung
      - Schmiere
      - beimischen
      - Ackergerät
      - vorliegen
      - Spielball
      - Sensation
      - Truppenteil
      - artikulieren
      - Mißklang
      - Mut
      - Gesichtsausdruck
      - Knotenpunkt
      - Einreichung
      - Unentschlossenheit
      - Abgesang
      - Lyzeum
      - vorweisen
      - Armenhaus
    url: https://zenodo.org/record/5796871/files/dwug_de.zip
  2.1.0:
    path: dwug_de/2.1.0
    standard_split:
      dev:
      - Abgesang
      - Einreichung
      - Dynamik
      - Sensation
      - Fuß
      - Ackergerät
      - Unentschlossenheit
      - Seminar
      - Mißklang
      - Schmiere
      - zersetzen
      - beimischen
      - überspannen
      - Truppenteil
      - Titel
      - abdecken
      - weitgreifend
      - Mut
      - ausspannen
      - abbauen
      - Spielball
      - Manschette
      - Engpaß
      - vergönnen
      - Mulatte
      test:
      - voranstellen
      - Gesichtsausdruck
      - vorliegen
      - Festspiel
      - Naturschönheit
      - Frechheit
      - Ohrwurm
      - Tier
      - artikulieren
      - Tragfähigkeit
      - Knotenpunkt
      - vorweisen
      - verbauen
      - Lyzeum
      - aufrechterhalten
      - Pachtzins
      - Entscheidung
      - Ausnahmegesetz
      - abgebrüht
      - Armenhaus
      - Behandlung
      - Rezeption
      - Kubikmeter
      - packen
      - Eintagsfliege
    url: https://zenodo.org/record/7295410/files/dwug_de.zip
