defaults:
  - preprocessing: toklem
  - spelling_normalization: swedish

name: dwug_sv
bert: KB/bert-base-swedish-cased
cleaning: null
test_on: null
groupings: ["1", "2"]
pairing: [COMPARE]
sampling: [annotated]

version: "2.0.0"
urls:
  "2.0.0": "https://zenodo.org/record/5801358/files/dwug_sv.zip"
  "1.0.0": "https://zenodo.org/record/5090648/files/dwug_sv.zip" 
_target_: src.dataset.Dataset