defaults:
  - _self_
  - preprocessing: toklem
  - spelling_normalization: null

name: dwug_en
bert: bert-base-uncased
cleaning: null
test_on: null
groupings: ["1", "2"]
version: 2.0.0

_target_: src.dataset.Dataset