_target_: src.dataset.Dataset
cleaning: null
defaults:
- preprocessing: toklem
- spelling_normalization: german
exclude_annotators: []
groupings:
- '1'
- '2'
pairing:
- COMPARE
sampling:
- annotated
type: dev
split: undefined
test_on: null
path: dwug_de_110
url: https://zenodo.org/record/5544198/files/dwug_de.zip