defaults:
  - preprocessing: toklem

name: dwug_es
bert: dccuchile/bert-base-spanish-wwm-uncased
cleaning: null
test_on: null
groupings: ["1", "2"]
version: 4.0.0
spelling_normalization: null

_target_: src.dataset.Dataset