defaults:
  - preprocessing: toklem
  - override preprocessing/spelling_normalization: null

name: dwug_en
cleaning: null
test_on: null
groupings: ["1", "2"]
version: 'latest'

_target_: src.dataset.Dataset