_target_: src.dataset.Dataset
cleaning: null
defaults:
  - preprocessing: ???
  - spelling_normalization: ???
  - split: ???
exclude_annotators: []
groupings:
  - "1"
  - "2"

wic_use_pairs:
  group: ALL
  sample: annotated
path: dwug_de_210
standard_split:
  dev:
    - abbauen
    - abdecken
    - abgebrüht
    - Abgesang
    - Ackergerät
    - Armenhaus
    - artikulieren
    - aufrechterhalten
    - Ausnahmegesetz
    - ausspannen
    - Behandlung
    - beimischen
    - Dynamik
    - Einreichung
    - Eintagsfliege
    - Engpaß
    - Entscheidung
    - Festspiel
    - Frechheit
    - Fuß
    - Gesichtsausdruck
    - Knotenpunkt
    - Kubikmeter
    - Lyzeum
    - Manschette
    - Mißklang
    - Mulatte
    - Mut
    - Naturschönheit
    - Ohrwurm
    - Pachtzins
    - packen
    - Rezeption
    - Schmiere
    - Seminar
    - Sensation
    - Spielball
    - Tier
    - Titel
    - Tragfähigkeit
    - Truppenteil
    - Unentschlossenheit
    - verbauen
    - vergönnen
    - voranstellen
    - vorliegen
    - vorweisen
    - weitgreifend
    - zersetzen
    - überspannen
  dev1:
    - vorliegen
    - vorweisen
    - Entscheidung
    - Mut
    - Naturschönheit
    - Sensation
    - Kubikmeter
    - Rezeption
    - abdecken
    - zersetzen
    - Tier
    - Spielball
    - Ausnahmegesetz
    - abbauen
    - überspannen
    - Fuß
    - Unentschlossenheit
    - Schmiere
    - Einreichung
    - Armenhaus
    - Knotenpunkt
    - Abgesang
    - Ackergerät
    - Titel
    - vergönnen
  dev2:
    - Ohrwurm
    - weitgreifend
    - artikulieren
    - aufrechterhalten
    - Behandlung
    - Lyzeum
    - ausspannen
    - Manschette
    - Festspiel
    - Pachtzins
    - packen
    - Eintagsfliege
    - voranstellen
    - Engpaß
    - abgebrüht
    - Gesichtsausdruck
    - Truppenteil
    - verbauen
    - beimischen
    - Dynamik
    - Frechheit
    - Mulatte
    - Seminar
    - Tragfähigkeit
    - Mißklang
  full:
    - abbauen
    - abdecken
    - abgebrüht
    - Abgesang
    - Ackergerät
    - Armenhaus
    - artikulieren
    - aufrechterhalten
    - Ausnahmegesetz
    - ausspannen
    - Behandlung
    - beimischen
    - Dynamik
    - Einreichung
    - Eintagsfliege
    - Engpaß
    - Entscheidung
    - Festspiel
    - Frechheit
    - Fuß
    - Gesichtsausdruck
    - Knotenpunkt
    - Kubikmeter
    - Lyzeum
    - Manschette
    - Mißklang
    - Mulatte
    - Mut
    - Naturschönheit
    - Ohrwurm
    - Pachtzins
    - packen
    - Rezeption
    - Schmiere
    - Seminar
    - Sensation
    - Spielball
    - Tier
    - Titel
    - Tragfähigkeit
    - Truppenteil
    - Unentschlossenheit
    - verbauen
    - vergönnen
    - voranstellen
    - vorliegen
    - vorweisen
    - weitgreifend
    - zersetzen
    - überspannen
  test: []
test_on: null
type: dev
url: https://zenodo.org/record/7295410/files/dwug_de.zip
