defaults:
  - _self_
  - optional preprocessing/spelling_normalization: null

name: dwug_sv
version: 'latest'
groupings: [1, 2]
preprocessing:
  _target_: src.preprocessing.toklem
  spelling_normalization: null



