_target_: src.dataset.Dataset
cleaning: null
defaults:
- _self_
- preprocessing: toklem
exclude_annotators: []
groupings:
- '1'
- '2'
name: dwug_la
pairing:
- COMPARE
sampling:
- annotated
spelling_normalization: null
split:
  how: standard
  use: dev
test_on: null
version: '1'
versions:
  '1':
    path: dwug_la/1
    standard_split:
      dev:
      - acerbus
      - hostis
      - potestas
      - beatus
      - nobilitas
      - senatus
      - nepos
      - sapientia
      - necessarius
      - dubius
      - scriptura
      - virtus
      - poena
      - sensus
      - adsumo
      - oportet
      - dolus
      - imperator
      - templum
      - simplex
      test:
      - titulus
      - honor
      - pontifex
      - consilium
      - itero
      - fidelis
      - licet
      - jus
      - salus
      - cohors
      - humanitas
      - ancilla
      - civitas
      - consul
      - sacramentum
      - regnum
      - dux
      - sanctus
      - voluntas
      - credo
    url: https://zenodo.org/record/5255228/files/dwug_la.zip
