_target_: src.dataset.Dataset
cleaning: null
defaults:
- _self_
- preprocessing: toklem
- spelling_normalization: english
exclude_annotators: []
groupings:
- '1'
- '2'
pairing:
- COMPARE
path: dwug_en_100
sampling:
- annotated
split: undefined
standard_split:
  dev: []
  dev1: []
  dev2: []
  full:
  - afternoon_nn
  - attack_nn
  - bag_nn
  - ball_nn
  - bar_nn
  - bit_nn
  - chairman_nn
  - chef_nn
  - circle_vb
  - contemplation_nn
  - donkey_nn
  - edge_nn
  - face_nn
  - fiction_nn
  - gas_nn
  - graft_nn
  - grain_nn
  - head_nn
  - heel_nn
  - include_vb
  - land_nn
  - lane_nn
  - lass_nn
  - maxim_nn
  - multitude_nn
  - ounce_nn
  - part_nn
  - pick_vb
  - pin_vb
  - plane_nn
  - player_nn
  - prop_nn
  - quilt_nn
  - rag_nn
  - rally_nn
  - record_nn
  - relationship_nn
  - risk_nn
  - savage_nn
  - stab_nn
  - stroke_vb
  - thump_nn
  - tip_vb
  - tree_nn
  - twist_nn
  - word_nn
  test:
  - afternoon_nn
  - attack_nn
  - bag_nn
  - ball_nn
  - bar_nn
  - bit_nn
  - chairman_nn
  - chef_nn
  - circle_vb
  - contemplation_nn
  - donkey_nn
  - edge_nn
  - face_nn
  - fiction_nn
  - gas_nn
  - graft_nn
  - grain_nn
  - head_nn
  - heel_nn
  - include_vb
  - land_nn
  - lane_nn
  - lass_nn
  - maxim_nn
  - multitude_nn
  - ounce_nn
  - part_nn
  - pick_vb
  - pin_vb
  - plane_nn
  - player_nn
  - prop_nn
  - quilt_nn
  - rag_nn
  - rally_nn
  - record_nn
  - relationship_nn
  - risk_nn
  - savage_nn
  - stab_nn
  - stroke_vb
  - thump_nn
  - tip_vb
  - tree_nn
  - twist_nn
  - word_nn
test_on: null
type: test
url: https://zenodo.org/record/5544444/files/dwug_en.zip
