_target_: src.dataset.Dataset
cleaning: null
defaults:
  - _self_
  - preprocessing: ???
  - spelling_normalization: ???
  - split: ???
exclude_annotators: []
groupings:
  - "1"
  - "2"
wic_use_pairs:
  group: ALL
  sample: annotated
path: dwug_en_resampled
standard_split:
  dev: []
  dev1: []
  dev2: []
  full:
    - attack_nn
    - bit_nn
    - circle_vb
    - edge_nn
    - graft_nn
    - head_nn
    - lane_nn
    - multitude_nn
    - ounce_nn
    - part_nn
    - player_nn
    - record_nn
    - stab_nn
    - thump_nn
    - twist_nn
    - word_nn
  test:
   - attack_nn
    - bit_nn
    - circle_vb
    - edge_nn
    - graft_nn
    - head_nn
    - lane_nn
    - multitude_nn
    - ounce_nn
    - part_nn
    - player_nn
    - record_nn
    - stab_nn
    - thump_nn
    - twist_nn
    - word_nn
test_on: null
type: test
url: https://zenodo.org/records/14025941/files/dwug_en_resampled.zip
