# the Dataset class also requires a `standard_split` argument
# however, Hydra cannot interpolate values in the defaults list with values 
# in the final config (i.e., outside the defaults list)
# therefore this field is added at runtime in utils/runner.py

defaults:
  - _self_
  - preprocessing: toklem
  - spelling_normalization: swedish

name: dwug_sv
cleaning: null
test_on: null
groupings: ["1", "2"]
pairing: [COMPARE]
sampling: [annotated]
standard_split: ${.name}_${.version}
exclude_annotators: []
split:
  how: standard
  use: dev

version: "2.0.0"
versions:
  2.0.0: 
    url: "https://zenodo.org/record/5801358/files/dwug_sv.zip"
    path: dwug_sv/2.0.0
  1.0.0: 
    url: "https://zenodo.org/record/5090648/files/dwug_sv.zip" 
    path: dwug_sv/1.0.0

_target_: src.dataset.Dataset