# the Dataset class also requires a `standard_split` argument
# however, Hydra cannot interpolate values in the defaults list with values 
# in the final config (i.e., outside the defaults list)
# therefore this field is added at runtime in utils/runner.py

defaults:
  - _self_
  - preprocessing: toklem

name: dwug_de
cleaning: null
test_on: null
groupings: ["1", "2"]
version: "1"
pairing: [COMPARE]
sampling: [annotated]
spelling_normalization: null

urls:
  "1": "https://zenodo.org/record/5255228/files/dwug_la.zip"

_target_: src.dataset.Dataset
