_target_: src.dataset.Dataset
cleaning: null
defaults:
  - _self_
  - preprocessing: ???
  - spelling_normalization: ???
exclude_annotators: []
groupings:
  - "1"
  - "2"
wic_use_pairs:
  group: ALL
  sample: annotated
path: dwug_es_400
split: undefined
standard_split:
  dev: []
  dev1: []
  dev2: []
  full:
    - abundar
    - actitud
    - adelante
    - agradecer
    - aguantar
    - albergar
    - arena
    - asolar
    - ataque
    - atrás
    - ausencia
    - avance
    - banco
    - canal
    - capital
    - cobrar
    - colaborar
    - compasión
    - contingente
    - copiar
    - corona
    - corredor
    - corriente
    - creciente
    - cólera
    - declinar
    - demá
    - descendiente
    - despacho
    - diligencia
    - disco
    - distribuir
    - educado
    - elocuente
    - empresa
    - encargado
    - enterar
    - escritor
    - especulación
    - fallar
    - fallecimiento
    - gracioso
    - historia
    - historiador
    - impulso
    - indicativo
    - instalación
    - interrogatorio
    - intolerable
    - juguete
    - maduro
    - maravilloso
    - marco
    - matiz
    - metal
    - metro
    - modificado
    - modo
    - mortal
    - mujer
    - médula
    - móvil
    - músculo
    - "no"
    - nombramiento
    - nombrar
    - obtener
    - pelear
    - pendiente
    - periodista
    - pila
    - planta
    - precursor
    - pretender
    - prima
    - propiamente
    - propuesta
    - próximo
    - quemar
    - recomendar
    - recordar
    - reforma
    - retroceder
    - saludar
    - satélite
    - servidor
    - sexo
    - socialista
    - solicitud
    - suposición
    - susceptible
    - tablero
    - tarea
    - trato
    - tropical
    - variedad
    - verdaderamente
    - viernes
    - visita
    - vuestro
  test:
    - actitud
    - ataque
    - atrás
    - ausencia
    - avance
    - banco
    - canal
    - capital
    - cobrar
    - colaborar
    - compasión
    - copiar
    - corriente
    - cólera
    - declinar
    - demá
    - diligencia
    - disco
    - distribuir
    - educado
    - elocuente
    - encargado
    - enterar
    - especulación
    - fallar
    - fallecimiento
    - historia
    - historiador
    - impulso
    - indicativo
    - juguete
    - maduro
    - maravilloso
    - marco
    - matiz
    - metal
    - metro
    - modificado
    - médula
    - nombrar
    - pendiente
    - pila
    - planta
    - prima
    - propiamente
    - próximo
    - recomendar
    - recordar
    - retroceder
    - satélite
    - socialista
    - solicitud
    - susceptible
    - tarea
    - trato
    - tropical
    - variedad
    - viernes
    - visita
    - vuestro
test_on: null
type: test
url: https://zenodo.org/record/6433667/files/dwug_es.zip
