defaults:
  - preprocessing: toklem
  - spelling_normalization: null

name: dwug_es
bert: dccuchile/bert-base-spanish-wwm-uncased
cleaning: null
test_on: null
groupings: ["1", "2"]
version: 4.0.0

_target_: src.dataset.Dataset