_target_: src.dataset.Dataset
cleaning: null
defaults:
  - preprocessing: ???
  - spelling_normalization: ???
  - split: ???
exclude_annotators: []
groupings:
  - "1"
  - "2"
wic_use_pairs:
  group: ALL
  sample: annotated
path: dwug_de_sense/misc/dwug_de_sense
test_on: null
type: dev
url: https://zenodo.org/record/7441645/files/dwug_de.zip
