# the Dataset class also requires a `standard_split` argument
# however, Hydra cannot interpolate values in the defaults list with values 
# in the final config (i.e., outside the defaults list)
# therefore this field is added at runtime in utils/runner.py

defaults:
  - _self_
  - preprocessing: toklem

name: dwug_es
cleaning: null
test_on: null
groupings: ["1", "2"]
version: "4.0.0"
spelling_normalization: null
pairing: [COMPARE]
sampling: [annotated]

urls:
  "4.0.0": "https://zenodo.org/record/6433667/files/dwug_es.zip"
  "3.0.0": "https://zenodo.org/record/6433398/files/dwug_es.zip"
  "2.0.0": "https://zenodo.org/record/6433350/files/dwug_es.zip"
  "1.0.1": "https://zenodo.org/record/6433203/files/dwug_es.zip"
  "1.0.0": "https://zenodo.org/record/6300105/files/dwug_es.zip"

_target_: src.dataset.Dataset