_target_: src.dataset.Dataset
cleaning: null
defaults:
  - _self_
  - preprocessing: ???
  - spelling_normalization: none
  - split: ???
exclude_annotators: []
groupings:
  - "1"
  - "2"
wic_use_pairs:
  group: ALL
  sample: annotated
path: nor_dia_change/subset1_cleaned
type: dev
test_on: null
url: https://drive.google.com/file/d/1nmObcDM5hM6beKubOUXOQW3fPUVL6_5Q/view?usp=sharing
