_target_: src.dataset.Dataset
cleaning: null
defaults:
  - _self_
  - preprocessing: ???
  - spelling_normalization: ???
  - split: ???
exclude_annotators: []
groupings:
  - "1"
  - "2"
wic_use_pairs:
  group: ALL
  sample: annotated
path: refwug_110
standard_split:
  dev: []
  dev1: []
  dev2: []
  full:
    - Abend
    - Anstalt
    - Anstellung
    - Bilanz
    - billig
    - Donnerwetter
    - englisch
    - Feder
    - Feine
    - flott
    - geharnischt
    - Kinderstube
    - locker
    - Motiv
    - Museum
    - packen
    - Presse
    - Reichstag
    - Steckenpferd
    - technisch
    - Vorwort
    - Zufall
  test:
    - Abend
    - Anstalt
    - Anstellung
    - Bilanz
    - billig
    - Donnerwetter
    - englisch
    - Feder
    - Feine
    - flott
    - geharnischt
    - Kinderstube
    - locker
    - Motiv
    - Museum
    - packen
    - Presse
    - Reichstag
    - Steckenpferd
    - technisch
    - Vorwort
    - Zufall
test_on: null
type: test
url: https://zenodo.org/record/5791269/files/refwug.zip
