_target_: src.dataset.Dataset
cleaning: null
defaults:
- _self_
- preprocessing: toklem
- spelling_normalization: german
exclude_annotators: []
groupings:
- '1'
- '2'
name: refwug
pairing:
- COMPARE
sampling:
- annotated
split:
  how: standard
  use: dev
test_on: null
version: 1.1.0
versions:
  1.0.0:
    path: refwug/1.0.0
    standard_split:
      dev:
      - Feder
      - Bilanz
      - Museum
      - geharnischt
      - englisch
      - Steckenpferd
      - Donnerwetter
      - billig
      - Feine
      - Anstellung
      - Reichstag
      test:
      - Motiv
      - Kinderstube
      - flott
      - technisch
      - Vorwort
      - Zufall
      - Anstalt
      - packen
      - Presse
      - locker
      - Abend
    url: https://zenodo.org/record/5544578/files/refwug.zip
  1.1.0:
    path: refwug/1.1.0
    standard_split:
      dev:
      - Bilanz
      - technisch
      - Reichstag
      - packen
      - Motiv
      - billig
      - geharnischt
      - Presse
      - englisch
      - Feder
      - flott
      test:
      - Steckenpferd
      - Kinderstube
      - Anstellung
      - Vorwort
      - Zufall
      - Donnerwetter
      - Anstalt
      - locker
      - Abend
      - Feine
      - Museum
    url: https://zenodo.org/record/5791269/files/refwug.zip
