defaults:
  - preprocessing: toklem
  - spelling_normalization: german

name: dwug_de
cleaning: null
test_on: null
groupings: ["1", "2"]
version: "1.1.0"
pairing: [COMPARE]
sampling: [annotated]

urls:
  "1.1.0": "https://zenodo.org/record/5791269/files/refwug.zip",
  "1.0.0": "https://zenodo.org/record/5544578/files/refwug.zip"

_target_: src.dataset.Dataset

