_target_: src.dataset.Dataset
cleaning: null
defaults:
  - preprocessing: ???
  - spelling_normalization: none
exclude_annotators: []
groupings:
  - "1"
  - "2"
wic_use_pairs:
  group: ALL
  sample: annotated
path: RuSemShift/rusemshift_2/DWUG
split: undefined
standard_split:
  dev:
    - ателье
    - бескомпромиссность
    - беспредел
    - благотворительность
    - блочный
    - боевик
    - ботаник
    - брезентовый
    - валюта
    - валютный
    - вампир
    - взлом
    - вирус
    - выплеск
    - высоколобый
    - вышка
    - гермафродит
    - гильдия
    - гимназия
    - глянец
    - гололед
    - голубой
    - двушка
    - дивизион
    - донорство
    - драйвер
    - завязка
    - загрузка
    - знамя
    - игра
    - инкубатор
    - исполнитель
    - карта
    - классный
    - корпус
    - лилипут
    - ломберный
    - мгновение
    - модель
    - мыло
    - одежда
    - однодневка
    - орбита
    - осуществимый
    - пакет
    - партиец
    - перестройка
    - погрешность
    - подстава
    - предощущение
    - приношение
    - прислуга
    - приставка
    - провальный
    - продукция
    - раскрутка
    - рождество
    - рынок
    - рыночный
    - свинцовый
    - собака
    - сомнение
    - стаканчик
    - стачка
    - стиль
    - удвоение
    - флакон
    - четырехлетка
    - эрмитажный
  dev1:
    - прислуга
    - стиль
    - голубой
    - боевик
    - провальный
    - флакон
    - орбита
    - раскрутка
    - собака
    - драйвер
    - перестройка
    - рождество
    - приставка
    - корпус
    - валютный
    - ботаник
    - бескомпромиссность
    - вирус
    - валюта
    - карта
    - погрешность
    - сомнение
    - исполнитель
    - вышка
    - беспредел
    - пакет
    - загрузка
    - мгновение
    - благотворительность
    - приношение
    - брезентовый
    - донорство
    - лилипут
    - двушка
  dev2:
    - стачка
    - предощущение
    - выплеск
    - ателье
    - взлом
    - глянец
    - продукция
    - высоколобый
    - ломберный
    - модель
    - подстава
    - мыло
    - завязка
    - дивизион
    - эрмитажный
    - одежда
    - однодневка
    - классный
    - рынок
    - четырехлетка
    - гимназия
    - гильдия
    - инкубатор
    - гололед
    - гермафродит
    - осуществимый
    - вампир
    - свинцовый
    - знамя
    - рыночный
    - блочный
    - стаканчик
    - игра
    - удвоение
    - партиец
  full:
    - ателье
    - бескомпромиссность
    - беспредел
    - благотворительность
    - блочный
    - боевик
    - ботаник
    - брезентовый
    - валюта
    - валютный
    - вампир
    - взлом
    - вирус
    - выплеск
    - высоколобый
    - вышка
    - гермафродит
    - гильдия
    - гимназия
    - глянец
    - гололед
    - голубой
    - двушка
    - дивизион
    - донорство
    - драйвер
    - завязка
    - загрузка
    - знамя
    - игра
    - инкубатор
    - исполнитель
    - карта
    - классный
    - корпус
    - лилипут
    - ломберный
    - мгновение
    - модель
    - мыло
    - одежда
    - однодневка
    - орбита
    - осуществимый
    - пакет
    - партиец
    - перестройка
    - погрешность
    - подстава
    - предощущение
    - приношение
    - прислуга
    - приставка
    - провальный
    - продукция
    - раскрутка
    - рождество
    - рынок
    - рыночный
    - свинцовый
    - собака
    - сомнение
    - стаканчик
    - стачка
    - стиль
    - удвоение
    - флакон
    - четырехлетка
    - эрмитажный
  test: []
test_on: null
type: dev
url: https://github.com/juliarodina/RuSemShift.git
