_target_: src.dataset.Dataset
cleaning: null
defaults:
  - preprocessing: toklem
exclude_annotators: []
groupings:
  - "1"
  - "2"
wic_use_pairs:
  group: ALL
  sample: annotated
path: RuSemShift/rusemshift_1/DWUG
spelling_normalization: null
split: undefined
standard_split:
  dev:
    - агентство
    - археолог
    - богадельня
    - больница
    - бюрократ
    - весна
    - вино
    - влажный
    - войско
    - вывеска
    - графиня
    - декрет
    - директор
    - дождь
    - дума
    - заведующий
    - заключенный
    - защитник
    - знатный
    - казенный
    - классный
    - клиника
    - комиссар
    - мазь
    - мама
    - машина
    - молодец
    - насаждение
    - неудачник
    - новичок
    - ночлег
    - обвинитель
    - овес
    - особа
    - отдел
    - отделение
    - отрывок
    - пакет
    - палата
    - передовой
    - переулок
    - пионер
    - похищение
    - правитель
    - привет
    - присутствие
    - прозвище
    - пружина
    - публика
    - свалка
    - сволочь
    - секция
    - серединный
    - смотритель
    - собор
    - ссора
    - стиль
    - тетка
    - торжественный
    - трибунал
    - тройка
    - трубка
    - уклон
    - управа
    - управление
    - участок
    - философ
    - червяк
    - чиновник
    - элемент
    - юношество
  dev1:
    - трибунал
    - вино
    - серединный
    - юношество
    - археолог
    - ночлег
    - червяк
    - вывеска
    - пионер
    - сволочь
    - богадельня
    - привет
    - присутствие
    - палата
    - похищение
    - управление
    - казенный
    - влажный
    - комиссар
    - заключенный
    - защитник
    - передовой
    - обвинитель
    - собор
    - овес
    - участок
    - неудачник
    - уклон
    - отдел
    - публика
    - весна
    - философ
    - дума
    - бюрократ
    - графиня
    - стиль
  dev2:
    - управа
    - машина
    - классный
    - пакет
    - декрет
    - элемент
    - смотритель
    - мама
    - насаждение
    - молодец
    - правитель
    - трубка
    - заведующий
    - директор
    - особа
    - свалка
    - новичок
    - тетка
    - торжественный
    - агентство
    - знатный
    - тройка
    - прозвище
    - дождь
    - клиника
    - больница
    - пружина
    - отделение
    - войско
    - секция
    - отрывок
    - переулок
    - мазь
    - ссора
    - чиновник
  full:
    - агентство
    - археолог
    - богадельня
    - больница
    - бюрократ
    - весна
    - вино
    - влажный
    - войско
    - вывеска
    - графиня
    - декрет
    - директор
    - дождь
    - дума
    - заведующий
    - заключенный
    - защитник
    - знатный
    - казенный
    - классный
    - клиника
    - комиссар
    - мазь
    - мама
    - машина
    - молодец
    - насаждение
    - неудачник
    - новичок
    - ночлег
    - обвинитель
    - овес
    - особа
    - отдел
    - отделение
    - отрывок
    - пакет
    - палата
    - передовой
    - переулок
    - пионер
    - похищение
    - правитель
    - привет
    - присутствие
    - прозвище
    - пружина
    - публика
    - свалка
    - сволочь
    - секция
    - серединный
    - смотритель
    - собор
    - ссора
    - стиль
    - тетка
    - торжественный
    - трибунал
    - тройка
    - трубка
    - уклон
    - управа
    - управление
    - участок
    - философ
    - червяк
    - чиновник
    - элемент
    - юношество
  test: []
test_on: null
type: dev
url: https://github.com/juliarodina/RuSemShift.git
