_target_: src.dataset.Dataset
cleaning: null
defaults:
- preprocessing: toklem
exclude_annotators: []
groupings:
- '1'
- '2'
name: rushifteval
pairing:
- COMPARE
sampling:
- annotated
spelling_normalization: null
split:
  how: standard
  use: dev
test_on: null
version: ???
versions:
  '1':
    path: rushifteval/durel/rushifteval1
    standard_split:
      dev:
      - расчет
      - дядька
      - уклад
      - пролетарий
      - живот
      - сверстник
      - стипендия
      - бригада
      - цензура
      - формула
      - полоса
      - любовь
      - писк
      - карман
      - издательство
      - полукруг
      - итальянец
      - веер
      - штаб
      - чек
      - проникновение
      - ссылка
      - лечение
      - лох
      - заблуждение
      - стена
      - апостол
      - закладка
      - четверть
      - советчик
      - частица
      - удобство
      - благодарность
      - формат
      - лишение
      - радикал
      - спутник
      - кулиса
      - брат
      - памятник
      - амбиция
      - железо
      - правда
      - тачка
      - понедельник
      - жесть
      - установление
      - название
      - кабан
      - дядя
      - полость
      - риторика
      - облако
      - головка
      - связка
      - возраст
      test:
      - дух
      - эшелон
      - роспись
      - прорыв
      - локоть
      - пафос
      - половинка
      - стол
      - союзник
      - наложение
      - верховье
      - вызов
      - юбилей
      - ядро
      - обоснование
      - хор
      - огонь
      - список
      - ранец
      - маньяк
      - линейка
      - ясли
      - тупик
      - размышление
      - хрен
      - помощник
      - путь
      - поэзия
      - земля
      - любовник
      - крушение
      - авторитет
      - наволочка
      - прецедент
      - собрат
      - крыша
      - совершенство
      - план
      - блин
      - центр
      - цифра
      - увольнение
      - век
      - грех
      - поколение
      - фаворит
      - завод
      - университет
      - промышленность
      - монстр
      - хозяйка
      - блондин
      - поставщик
      - предательство
      - углеводород
    url: https://github.com/akutuzov/rushifteval_public.git
  '2':
    path: rushifteval/durel/rushifteval2
    standard_split:
      dev:
      - цензура
      - цифра
      - прецедент
      - уклад
      - поколение
      - линейка
      - бригада
      - локоть
      - частица
      - вызов
      - сверстник
      - кулиса
      - эшелон
      - формула
      - обоснование
      - железо
      - крыша
      - огонь
      - верховье
      - жесть
      - пафос
      - головка
      - план
      - список
      - лох
      - поставщик
      - ясли
      - понедельник
      - ранец
      - лечение
      - полукруг
      - апостол
      - итальянец
      - университет
      - дядя
      - завод
      - чек
      - совершенство
      - авторитет
      - хрен
      - монстр
      - расчет
      - заблуждение
      - собрат
      - прорыв
      - амбиция
      - памятник
      - полоса
      - установление
      - связка
      - писк
      - лишение
      - закладка
      - хор
      - маньяк
      - тупик
      test:
      - дух
      - роспись
      - половинка
      - стол
      - живот
      - союзник
      - наложение
      - карман
      - юбилей
      - ядро
      - дядька
      - штаб
      - спутник
      - возраст
      - размышление
      - стена
      - помощник
      - формат
      - радикал
      - путь
      - поэзия
      - ссылка
      - земля
      - кабан
      - любовник
      - крушение
      - стипендия
      - название
      - веер
      - наволочка
      - облако
      - советчик
      - блин
      - четверть
      - центр
      - проникновение
      - пролетарий
      - увольнение
      - век
      - удобство
      - грех
      - благодарность
      - любовь
      - брат
      - фаворит
      - тачка
      - издательство
      - правда
      - промышленность
      - полость
      - хозяйка
      - блондин
      - риторика
      - предательство
      - углеводород
    url: https://github.com/akutuzov/rushifteval_public.git
  '3':
    path: rushifteval/durel/rushifteval3
    standard_split:
      dev:
      - цифра
      - крыша
      - наволочка
      - любовь
      - итальянец
      - увольнение
      - проникновение
      - амбиция
      - расчет
      - памятник
      - углеводород
      - живот
      - лишение
      - головка
      - вызов
      - сверстник
      - дядька
      - совершенство
      - полоса
      - половинка
      - прорыв
      - формат
      - центр
      - промышленность
      - хозяйка
      - линейка
      - завод
      - цензура
      - дядя
      - стена
      - понедельник
      - огонь
      - лох
      - помощник
      - веер
      - риторика
      - блондин
      - радикал
      - грех
      - блин
      - закладка
      - издательство
      - локоть
      - авторитет
      - правда
      - эшелон
      - пролетарий
      - кабан
      - название
      - апостол
      - спутник
      - хор
      - удобство
      - поэзия
      - формула
      - ссылка
      test:
      - частица
      - дух
      - бригада
      - роспись
      - пафос
      - стол
      - союзник
      - наложение
      - верховье
      - карман
      - юбилей
      - чек
      - ядро
      - штаб
      - обоснование
      - список
      - лечение
      - ранец
      - маньяк
      - ясли
      - тупик
      - связка
      - возраст
      - размышление
      - хрен
      - путь
      - земля
      - любовник
      - крушение
      - стипендия
      - прецедент
      - собрат
      - облако
      - план
      - советчик
      - четверть
      - век
      - писк
      - благодарность
      - поколение
      - брат
      - уклад
      - установление
      - заблуждение
      - железо
      - фаворит
      - тачка
      - кулиса
      - жесть
      - университет
      - полукруг
      - монстр
      - полость
      - поставщик
      - предательство
    url: https://github.com/akutuzov/rushifteval_public.git
