_target_: src.dataset.Dataset
cleaning: null
defaults:
- preprocessing: toklem
exclude_annotators: []
groupings:
- '1'
- '2'
pairing:
- COMPARE
path: rushifteval_public/durel/rushifteval3
sampling:
- annotated
spelling_normalization: null
split: undefined
standard_split:
  dev: []
  dev1: []
  dev2: []
  full:
  - авторитет
  - амбиция
  - апостол
  - благодарность
  - блин
  - блондин
  - брат
  - бригада
  - веер
  - век
  - верховье
  - возраст
  - вызов
  - головка
  - грех
  - дух
  - дядька
  - дядя
  - железо
  - жесть
  - живот
  - заблуждение
  - завод
  - закладка
  - земля
  - издательство
  - итальянец
  - кабан
  - карман
  - крушение
  - крыша
  - кулиса
  - лечение
  - линейка
  - лишение
  - локоть
  - лох
  - любовник
  - любовь
  - маньяк
  - монстр
  - наволочка
  - название
  - наложение
  - облако
  - обоснование
  - огонь
  - памятник
  - пафос
  - писк
  - план
  - поколение
  - половинка
  - полоса
  - полость
  - полукруг
  - помощник
  - понедельник
  - поставщик
  - поэзия
  - правда
  - предательство
  - прецедент
  - пролетарий
  - промышленность
  - проникновение
  - прорыв
  - путь
  - радикал
  - размышление
  - ранец
  - расчет
  - риторика
  - роспись
  - сверстник
  - связка
  - собрат
  - совершенство
  - советчик
  - союзник
  - список
  - спутник
  - ссылка
  - стена
  - стипендия
  - стол
  - тачка
  - тупик
  - увольнение
  - углеводород
  - удобство
  - уклад
  - университет
  - установление
  - фаворит
  - формат
  - формула
  - хозяйка
  - хор
  - хрен
  - цензура
  - центр
  - цифра
  - частица
  - чек
  - четверть
  - штаб
  - эшелон
  - юбилей
  - ядро
  - ясли
  test:
  - авторитет
  - амбиция
  - апостол
  - благодарность
  - блин
  - блондин
  - брат
  - бригада
  - веер
  - век
  - верховье
  - возраст
  - вызов
  - головка
  - грех
  - дух
  - дядька
  - дядя
  - железо
  - жесть
  - живот
  - заблуждение
  - завод
  - закладка
  - земля
  - издательство
  - итальянец
  - кабан
  - карман
  - крушение
  - крыша
  - кулиса
  - лечение
  - линейка
  - лишение
  - локоть
  - лох
  - любовник
  - любовь
  - маньяк
  - монстр
  - наволочка
  - название
  - наложение
  - облако
  - обоснование
  - огонь
  - памятник
  - пафос
  - писк
  - план
  - поколение
  - половинка
  - полоса
  - полость
  - полукруг
  - помощник
  - понедельник
  - поставщик
  - поэзия
  - правда
  - предательство
  - прецедент
  - пролетарий
  - промышленность
  - проникновение
  - прорыв
  - путь
  - радикал
  - размышление
  - ранец
  - расчет
  - риторика
  - роспись
  - сверстник
  - связка
  - собрат
  - совершенство
  - советчик
  - союзник
  - список
  - спутник
  - ссылка
  - стена
  - стипендия
  - стол
  - тачка
  - тупик
  - увольнение
  - углеводород
  - удобство
  - уклад
  - университет
  - установление
  - фаворит
  - формат
  - формула
  - хозяйка
  - хор
  - хрен
  - цензура
  - центр
  - цифра
  - частица
  - чек
  - четверть
  - штаб
  - эшелон
  - юбилей
  - ядро
  - ясли
test_on: null
type: test
url: https://github.com/akutuzov/rushifteval_public.git
