# the Dataset class also requires a `standard_split` argument
# however, Hydra cannot interpolate values in the defaults list with values 
# in the final config (i.e., outside the defaults list)
# therefore this field is added at runtime in utils/runner.py

defaults:
  - _self_
  - preprocessing: toklem
  - spelling_normalization: german

name: surel
cleaning: null
test_on: null
groupings: ["1", "2"]
version: "3.0.0"
pairing: [COMPARE]
sampling: [annotated]
standard_split: ${.name}_${.version}
exclude_annotators: []
split:
  how: standard
  use: dev

_target_: src.dataset.Dataset

versions:
  3.0.0: 
    url: "https://zenodo.org/record/5784569/files/surel.zip"
    path: surel/3.0.0
  2.0.0: 
    url: "https://zenodo.org/record/5543348/files/surel.zip"
    path: surel/2.0.0