defaults:
  - preprocessing: toklem
  - spelling_normalization: german

name: dwug_de
bert: bert-base-german-cased
cleaning: null
test_on: null
groupings: ["1", "2"]
version: "3.0.0"
pairing: [COMPARE]
sampling: [annotated]

_target_: src.dataset.Dataset

urls:
  "3.0.0": "https://zenodo.org/record/5784569/files/surel.zip"
  "2.0.0": "https://zenodo.org/record/5543348/files/surel.zip"
  "1.0.0": "https://zenodo.org/record/5543307/files/SURel.zip"