_target_: src.dataset.Dataset
cleaning: null
defaults:
  - _self_
  - preprocessing: ???
  - spelling_normalization: ???
exclude_annotators: []
groupings:
  - "1"
  - "2"
wic_use_pairs:
  group: ALL
  sample: annotated
path: surel_300
split: undefined
standard_split:
  dev: []
  dev1: []
  dev2: []
  full:
    - abschrecken
    - Blech
    - Eiweiß
    - Form
    - Gemüse
    - Gericht
    - Glas
    - Hamburger
    - Mandel
    - Messer
    - Messerspitze
    - Paprika
    - Prise
    - Rum
    - Salz
    - schlagen
    - Schnee
    - Schnittlauch
    - Schokolade
    - Schuß
    - Strudel
    - trennen
  test:
    - abschrecken
    - Blech
    - Eiweiß
    - Form
    - Gemüse
    - Gericht
    - Glas
    - Hamburger
    - Mandel
    - Messer
    - Messerspitze
    - Paprika
    - Prise
    - Rum
    - Salz
    - schlagen
    - Schnee
    - Schnittlauch
    - Schokolade
    - Schuß
    - Strudel
    - trennen
test_on: null
type: test
url: https://zenodo.org/record/5784569/files/surel.zip
