_target_: src.dataset.Dataset
cleaning: null
defaults:
- preprocessing: ???
- spelling_normalization: ???
- split: ???
exclude_annotators: []
groupings:
- '1'
- '2'
path: testwug_en
standard_split:
  dev:
  - afternoon_nn
  - arm
  - target
  - plane_nn
  dev1:
  - afternoon_nn
  - target
  dev2:
  - plane_nn
  - arm
  full:
  - afternoon_nn
  - arm
  - target
  - plane_nn
  test: []
test_on: null
type: dev
url: https://zenodo.org/record/7946753/files/testwug_en.zip
wic_use_pairs:
  group: ALL
  sample: annotated
