defaults:
  - override hydra/job_logging: custom


dataset:
  name: null
  version: 'latest'
  path: null
  groupings: [1, 2]
  targets: null
  preprocessing:
    module: src/preprocessing.py
    method: toklem
  cleaning:
    stats: {}
    method: all
  orthography: 
    normalize: true
    translation_table:
      german:
        aͤ: ä 
        oͤ: ö 
        uͤ: ü 
        Aͤ: Ä 
        Oͤ: Ö 
        Uͤ: Ü
        ſ: s 
        \ua75b: r 
        m̃: mm 
        æ: ae 
        Æ: Ae
        göñ: gönn
        spañ: spann
      # english:
      #   " \'s": "\'s" 
      #   " n\'t": "n\'t" 
      #   " \'ve": "\'ve" 
      #   " \'d' : "\'d" 
      #   " \'re": "\'re" 
      #   " \'ll": "\'ll'
      # swedish:
      #   " \'s": "\'s'




gpu: null


model: 
  name: ???
  truncation:
    tokens_before: 0.5
  layers: [1, -1]
  layer_aggregation: average
  subword_aggregation: average
  measure:
    module: src/measures.py
    method: apd_compare_all
    # clustering:
    #   module: src/clustering.py
    #   method: clustering_spectral



evaluation:
  task: ???

hydra:
  job:
    chdir: true
