defaults:
  - override hydra/job_logging: custom


dataset:
  name: null
  version: 'latest'
  path: null
  groupings: [1, 2]
  targets: null
  preprocessing:
    module: src/preprocessing.py
    method: toklem
  cleaning:
    stats: {}
    method: all
  orthography: 
    normalize: true
    translation_table: config/spelling_normalization.json




gpu: null


model: 
  name: "???"
  truncation:
    tokens_before: 0.5
  layers: [1, -1]
  layer_aggregation: average
  subword_aggregation: average
  measure:
    module: src/measures.py
    method: apd_compare_all
    # clustering:
    #   module: src/clustering.py
    #   method: clustering_spectral



evaluation:
  task: ???

hydra:
  job:
    chdir: true
