defaults:
  - override hydra/job_logging: custom


dataset:
  name: null
  version: 'latest'
  path: null
task: lscd
groupings: [1, 2]
test_targets: null
preprocessing:
  module: src/preprocessing.py
  method: null
  params: {}
cleaning:
  stats: {}
  method: all

gpu: null

model: '???'
layers: [1, -1]
layer_aggregation: average
measure:
  module: src/measures.py
  method: apd_compare_all
  method_params: {}
  sampling_params: {}
subword_aggregation: average

evaluation:
  task: '???'
  binary_threshold:
    module: src/threshold.py
    method: mean_std
    params:
      t: 0.1

hydra:
  job:
    chdir: true
