dataset:
  name: '???'
  task: lscd
  groupings: [1, 2]
  preprocessing:
    module: src/preprocessing.py
    method: null
    params: {}
  cleaning:
    stats: {}
    method: all


model:
  gpu: null
  name: '???'
  layers: [1, -1]
  layer_aggregation: average
  measure: 
    module: src/measures.py
    method: apd_compare_all
    method_params: {}
    sampling_params: {}
  subword_aggregation: average

evaluation:
  task: '???'
  binary_threshold:
    module: src/threshold.py
    method: null
    params: {}

hydra:
  job:
    chdir: true