name: dwug_es
language: es
task: lscd
grouping_1: 1
grouping_2: 2
uses:
  type: all
#  params:
#    n: 100
#    replacement: true
  pairing: COMPARE
  normalization: all # we sample COMPARE pairs, and all pairs
  # (all uses mixed in one set from uses1 uses2 with all possible combinations)
#  params:
#    n: 100
#    replacement: false
preprocessing:
  method: toklem
  params:
    cached: true
#    save: true